config/routes.rb
Rails.application.routes.draw do

  resources :travels, only: :none do
    collection do
      get :estimate
      post :converter
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  def estimate
  end

  def converter
    @estimate = params[:estimate]
    destiny = params[:destiny]

    @country = Travels::UpdateEstimate.country(destiny)
    @estimate_updated = Travels::UpdateEstimate.convert_estimate(@estimate, @country[:currencies][0][:code])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/travels_helper.rb
module TravelsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelExpensesConverter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/travels/converter.html.erb
<div class="container" style="margin-top: 200px">
  Sua viagem para <%= @country[:name] %> custará <%= @country[:currencies][0][:symbol] %> <%= '%.2f' % @estimate_updated %> <%= @country[:currencies][0][:name].split.last %>.
</div>

app/views/travels/estimate.html.erb
<div class="container" style="margin-top: 200px">
  <h2>Sua viagem começa aqui</h2>

  <%= form_with(url: converter_travels_path, method: :post, id: 'form-estimate') do |form| %>

    <div class="form-group row">
      <%= form.label :estimate, 'Orçamento em reais (R$)', class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= form.number_field :estimate, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group row">
      <%= form.label :destiny, "Destino", class: 'col-sm-2 col-form-label' %>
      <div class="col-sm-10">
        <%= form.select :destiny, Travels::UpdateEstimate.all_countries,{ include_blank: 'Selecione:'}, { class: 'form-select', required: true, "aria-label":"Default select example" } %>
      </div>
    </div>

    <button class="btn btn-primary" type="submit" id="btn-converter">Converter</button>
  <% end %>
</div>